### PR TITLE
more flexible data handling

### PR DESCRIPTION
**Pull request by frnsys**
I have been testing data from our mongo instances against atoll, and there was some mismatch as expected. I realized because mongo has a "flexible" schema (i.e. there's no guarantee that any given field will be present), the metric functions need to be able to declare which fields they need and detect when they are present.

This pull request implements a decorator, `requires_keys` which is used to specify which fields a metric function requires. For example:

```python
from coral.metrics.common import requires_keys
@requires_keys('foo.bar', 'foo.sup')
def my_metric(obj):
    return obj['foo']['bar'] + obj['foo']['sup']
```

The metric will return `None` if its required keys are unavailable.

So in the example, if `{'foo': {'bar': 10, 'sup': 5}}` was passed, the function would return `15`. However, if `{'foo': {}}` were passed, the function would return `None`.

This PR also adds an additional pipe to each of the scoring pipelines which removes metrics that have `None` as their value, assuming that they could not be computed.

All the existing metrics and pipelines have been updated for this.

### CODE REVIEW

**Comment by frnsys** [comment]
One question is whether I should use the mongo id field (`_id`) as the canonical id or the `id` field, which is present on some but not all objects.

similarly, for comments should I rely on the `parent_d` key, which points to the parent comment's mongo id, or `parent_id`, which seems to be left over from the data import?

@jde

**Comment by gabelula** [comment]
_id should be presented in all documents, where is not? I will look at the parent_d because it is a bug. It should be parent_id

**Comment by frnsys** [comment]
@gabelula `_id` is on all documents but some also have an `id` field (without the underscore) - I wasn't sure which one I should be using. It sounds like I should just use `_id`?

**Comment by frnsys** [comment]
@jde I can add in support for Actions. I haven't found any in the database yet - do you know if we've imported them yet? otherwise, I can just guess at what the keys will be.

**Pull request merged**
